name: Release Charts

on:
  push:
    branches:
      - test-update-operator

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: update sysdig-operator
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: sysdiglabs/sysdig-operator
          event-type: sysdig-release
          client-payload: '{"tag": "sysdig-1.12.70"}'